### ISSUE TITLE
Compute Damages based on stats and weapon

### ISSUE THREAD

**Issue by DeltaEvo** [aresrpg/aresrpg#106]
Depends on #13

- Add stats to player
- Check stats and weapon stats to compute damage

Old code
https://gist.github.com/DeltaEvo/dc807f93102b9e3013d46efd61ec30ec

**Comment by Sceat** [comment]
Originally the stats were made under Pingoo's direction he came from a world of warcraft environment while i was on the dofus side, since we rewrite aresrpg i'd like to make it more as how i wanted to design it in the past. Dofus and Wow are not compatible for the core systems, when we wrote aresrpg we took both world to create one and this created ambiguities. Here is how to make it work better in my opinion.

## Elements
Fire (Intelligence)
Earth (Strength)
Wind (Agility)
Water (Luck)

> Additional stats that can be manually increased by the player are `Health` and `Mind`

### Damages
There is only raw damages on aresrpg, for the warriors and vampires you have to up your `strength` to increase your damages (2 strength pts for 1damages), for bowmans you have to increase your `agility`, for mages it's the `intelligence`, this prevents players to build a multitude of compositions. Damages should be by elements so we have `wind` warriors (could be rogues/assasins), and `fire` bowmans and so on. There was discussions about class specialization like a mages could become a witcher etc but this was never implemented.

### Defense
Defense system is good, but should also use the multi elements system so we have defense against `fire`, defense against `water` etc, these a raw values of damage reduction which are provided by equipments only instead of raw stats 

### Dodge
Dodge is a percent chance of avoiding damages, it should be removed

### Dexterity
It was a value to increase critical damages, this should be removed and directly indicated on weapons and spells (a sword is 5 - 10 of damages, and 20 in case of a critical hit)

### Armor perforation
Can't remember how it was used but the concept should be removed

### Critical hits
This should be induced by the `agility` stat and each weapons/spells should have the base critical chance, a sword can have as a base 1/50 chance of doing a critical hit. The player agility would increase these chances

### Mind
This was the health regeneration stat, it should stay the same

### Health
This was the health stat, it should stay the same

### Raw elements
Each elements increase their respective damages and also have an additional utilities

Intelligence: Increase healing abilities
Strength: Increase inventory space
Agility: Increase critical chances
Luck: Increase the looting chances

**Comment by ToufouMaster** [comment]
This is extremly interesting but we return Again at the same point

Do we have to continue making AresV1 or Apply new ideas to make finally AresV1.5

**Comment by DeltaEvo** [comment]
I think this should be discussed with game designers and not here :thinking:, for now I think it's better to stick with what gameplay worked in the past and iterate on that to see if it brings a real improvement

**Comment by Sceat** [comment]
> I think this should be discussed with game designers and not here , for now I think it's better to stick with what gameplay worked in the past and iterate on that to see if it brings a real improvement

For such a modification we can't start by implementing something else it has to be one or the other, it is totally changing how the game works, actually i would like to write it myself @ToufouMaster :grin: 

> stick with what gameplay worked in the past
Well i'm not afraid of that, copy pasting is what i do best lol and the dofus-like system is proven to work since 10+ years

**Comment by DeltaEvo** [comment]
> Well i'm not afraid of that, copy pasting is what i do best lol and the dofus-like system is proven to work since 10+ years

We are not MineDofus or DofusCraft

**Comment by Sceat** [comment]
Well we are MineWowFus and the gameplay would be better if we were MineWow or Dofucraft

**Comment by Vahelnir** [comment]
Why not a AresGacha server tho ?

**Comment by DeltaEvo** [comment]
> Well we are MineWowFus and the gameplay would be better if we were MineWow or Dofucraft

Better we don't know without comparing, and for now we can't compare

**Comment by ToufouMaster** [comment]
maybe you should unlock this issue considering i'm not working on the server due to the lack of time with the approaching exams (Baccalauréat)

**Comment by Sceat** [comment]
it's simply blocked because no decision was made yet
