### ISSUE TITLE
Reducer / Observer structure refactoring

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#136]
While implementing #103 i came across some ambiguous limitations, the design is going to evolve as follow:

`player state` -> can be reduced -> can be observed -> can impact other parties
`mob state` -> can be reduced -> can be observed -> can impact other parties

> would need the same for traders and world (world events that act on other parties)

It is basically the same thing as we currently have but way more structured and easy to understand

**Comment by Sceat** [comment]
- A mob spawning is induced by a player walking by, this mean the mobs observer have to watch players state events.
- A damage indicator appearing is induced by an entity taking damages, this mean the world observer have to watch both players and mobs states

**Comment by DeltaEvo** [comment]
Mob don't have a direct view, they are only viewed by the player, this simplifies a lot interactions, and since mob actions are only induced by player (Since only the player is "dynamic") this makes sens

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgc3RhdGUoKFN0YXRlKSlcbiAgYWN0aW9ucygoQWN0aW9ucykpXG4gIHZpZXcoKFZpZXcpKVxuICBtaW5lY3JhZnRbTWluZWNyYWZ0IENsaWVudF1cblxuICBzdHlsZSBzdGF0ZSBmaWxsOiMyOWI2ZjYsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcbiAgc3R5bGUgYWN0aW9ucyBmaWxsOiNlZjUzNTAsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcbiAgc3R5bGUgdmlldyBmaWxsOiM2NmJiNmEsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcblxuICBtc3RhdGUoKFN0YXRlKSlcbiAgbWFjdGlvbnMoKEFjdGlvbnMpKVxuXG4gIHN0eWxlIG1zdGF0ZSBmaWxsOiMyOWI2ZjYsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcbiAgc3R5bGUgbWFjdGlvbnMgZmlsbDojZWY1MzUwLGNvbG9yOndoaXRlLHN0cm9rZTpub25lXG5cbiAgc3ViZ3JhcGggY2xpZW50XG4gICAgYWN0aW9ucyAtLnJlZHVjZS4tPiBzdGF0ZVxuICAgIHZpZXcgLS5kaXNwYXRjaC4tPiBhY3Rpb25zXG4gICAgc3RhdGUgLS5vYnNlcnZlLi0-IHZpZXdcbiAgZW5kXG5cbiAgc3ViZ3JhcGggbW9iXG4gICAgbWFjdGlvbnMgLS5yZWR1Y2UuLT4gbXN0YXRlXG4gICAgdmlldyAtLmRpc3BhdGNoLi0-IG1hY3Rpb25zXG4gICAgbXN0YXRlIC0ub2JzZXJ2ZS4tPiB2aWV3XG4gIGVuZFxuXG4gIHN1YmdyYXBoIHByb3RvY29sXG4gICAgbWluZWNyYWZ0IC0tLSB2aWV3XG4gIGVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgc3RhdGUoKFN0YXRlKSlcbiAgYWN0aW9ucygoQWN0aW9ucykpXG4gIHZpZXcoKFZpZXcpKVxuICBtaW5lY3JhZnRbTWluZWNyYWZ0IENsaWVudF1cblxuICBzdHlsZSBzdGF0ZSBmaWxsOiMyOWI2ZjYsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcbiAgc3R5bGUgYWN0aW9ucyBmaWxsOiNlZjUzNTAsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcbiAgc3R5bGUgdmlldyBmaWxsOiM2NmJiNmEsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcblxuICBtc3RhdGUoKFN0YXRlKSlcbiAgbWFjdGlvbnMoKEFjdGlvbnMpKVxuXG4gIHN0eWxlIG1zdGF0ZSBmaWxsOiMyOWI2ZjYsY29sb3I6d2hpdGUsc3Ryb2tlOm5vbmVcbiAgc3R5bGUgbWFjdGlvbnMgZmlsbDojZWY1MzUwLGNvbG9yOndoaXRlLHN0cm9rZTpub25lXG5cbiAgc3ViZ3JhcGggY2xpZW50XG4gICAgYWN0aW9ucyAtLnJlZHVjZS4tPiBzdGF0ZVxuICAgIHZpZXcgLS5kaXNwYXRjaC4tPiBhY3Rpb25zXG4gICAgc3RhdGUgLS5vYnNlcnZlLi0-IHZpZXdcbiAgZW5kXG5cbiAgc3ViZ3JhcGggbW9iXG4gICAgbWFjdGlvbnMgLS5yZWR1Y2UuLT4gbXN0YXRlXG4gICAgdmlldyAtLmRpc3BhdGNoLi0-IG1hY3Rpb25zXG4gICAgbXN0YXRlIC0ub2JzZXJ2ZS4tPiB2aWV3XG4gIGVuZFxuXG4gIHN1YmdyYXBoIHByb3RvY29sXG4gICAgbWluZWNyYWZ0IC0tLSB2aWV3XG4gIGVuZCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

> A mob spawning is induced by a player walking by, this mean the mobs observer have to watch players state events.

You just need to invert that view, it's the player that will "spawn/respawn" the mob

>  would need the same for traders and world (world events that act on other parties)

Traders is only a mob that is shown to the player it doesn't have state and it don't need sto

And the world is only a constant source of truth (I know that the world is "recreated" for each player but it should not be like that, I need to change that) and as an event bus for "cross-view" communication

**Comment by Sceat** [comment]
That's correct, let's keep it simple
