### ISSUE TITLE
State is not saved when client error

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#305]
Quite often when a player disconnect, an client error is thrown which prevent the state from being saved here
```js
  aiter(
    combineAsyncIterators(
      actions[Symbol.asyncIterator](),
      packets,
      ...blockchain.sources
    )
  )
    .map(transform_action)
    .reduce(
      (last_state, action) => {
        const state = reduce_state(last_state, action)
        events.emit('state', state)
        return state
      },
      { ...initial_state, ...player_state }
    )
    .then(save_state)
    .catch(error => {
      // TODO: what to do here if we can't save the client ?
      log.error(error, 'State error')
    })
```

how can we get the final state to call `save_state` in a `.finally` ?

**Comment by DeltaEvo** [comment]
I observed that too. The root issue for me is that the "actions" stream and the reduce body should never throw errors, currently I guess that this is an unwanted behavior from `events.on` (it listen to the error event) on the packets stream

We could also as a mitigation (for future errors) for that to catch the error and try to save the get_state value, however I'm not a big fan of adding this now because we might in the future store the whole state updates of the player
