### ISSUE TITLE
Joining with an invalid version result with a disconnection after a timeout of 30 seconds

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#396]
Settings to `1.16.3`
i join with `1.16.5`
i punch a dumb chicken
i wait
i get kicked

**Comment by DeltaEvo** [comment]
It's really weird since https://github.com/PrismarineJS/minecraft-data/blob/master/data/dataPaths.json#L910 it should be the same protocol

**Comment by DeltaEvo** [comment]
Ok so after investigating this is a bug in node-minecraft-protocol, the client is ended since the protocol version don't match https://github.com/PrismarineJS/node-minecraft-protocol/blob/1796b9693d02be5fa8e6e4a03c547e430b0bf21d/src/server/handshake.js#L18 and since we are changing the serializer the connection is closed by the closeTimer https://github.com/PrismarineJS/node-minecraft-protocol/blob/1796b9693d02be5fa8e6e4a03c547e430b0bf21d/src/client.js#L182
